# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_application'),
        ('account', '0007_merge_20161029_1113'),
    ]

    operations = [
    ]
