---
language: python
sudo: false
dist: trusty
addons:
  chrome: stable
python:
  - '3.5'
  - '3.6'
  - '2.7'
before_install:
  - psql -c 'create database froide;' -U postgres
  - wget https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip -O /tmp/chromedriver
  - chmod 777 /tmp/chromedriver
install:
  - pip install -r requirements-test.txt
  - pip install psycopg2 coveralls
  - pip install -e .
script:
  - export CHROME_DRIVER_PATH=/tmp/chromedriver
  - export DATABASE_URL=postgres://postgres@127.0.0.1/froide
  - make test
after_success:
  - coveralls
