---
language: python
python:
- '2.7'
- '2.6'
services:
- elasticsearch
before_install:
- export PIP_USE_MIRRORS=true
- export PIP_INDEX_URL=https://simple.crate.io/
- phantomjs --version
install:
- pip install https://github.com/stefanw/terrarium/archive/develop.zip boto
- terrarium key requirements-test.txt
- terrarium --target froideenv --remote-key-format "u/stwe/froideenv/%(arch)s-%(python_vmajor)s.%(python_vminor)s-%(digest)s" install requirements-test.txt || (wget "http://resources.opendatalabs.org.s3.amazonaws.com/u/stwe/froideenv/`terrarium key requirements-test.txt`" ; terrarium --no-upload --s3-bucket "" --target froideenv --storage-dir . install requirements-test.txt)
- source froideenv/bin/activate
- which python
- pip install -e .
script:
- make test
branches:
  only:
  - master
env:
  global:
  - S3_BUCKET=resources.opendatalabs.org
  - S3_ACCESS_KEY=AKIAIY6JZKLHFPB3KTQA
  - secure: "B0JCveS4EwWZybclbEpFN1e/Am6uTTBU9qFJTFs0fyj8LBmdUl14YcWK+24O\nBiX9C3QUsfzHP5SoMEo3GgYZzLMIKRX8wr/UdspyW6sBh8VyPqfaanWys9xn\nGETJBJA30cYpUEwfEsNko/xz7TpW3dfP6O2hweSFuPo/Uzjt1tg="
