# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0004_auto_20161029_1425'),
        ('publicbody', '0011_auto_20180105_1648'),
    ]

    operations = [
    ]
